# Generated by Django 2.1.2 on 2018-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile', models.BigIntegerField(default=True, unique=True)),
                ('address', models.TextField(editable=False)),
                ('dob', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='default_pic.png', upload_to='register/')),
                ('password', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(editable=False, max_length=200)),
                ('api_key', models.TextField(editable=False)),
                ('session_id', models.CharField(default='', max_length=2000)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
